Pod::Spec.new do |s|
  s.name             = "BricksAndAgentPod"
  s.summary          = "This is for Brins And Agent static library pod for performance improvement."
  s.version          = "0.1.0"
  s.homepage         = "https://github.com/FlammerSL/BricksAndAgentPod"
  s.license          = 'MIT'
  s.author           = {"Isuru Ranasinghe" => "ranasinghe.i.u@gmail.com"}
  s.source           = { :git => "https://github.com/FlammerSL/BricksAndAgentPod.git", :tag => s.version.to_s }
  s.platform     = :ios, '10.0'
  s.requires_arc = true
  s.source_files = 'Source/**/*'
  s.swift_version = '5.0'
  s.frameworks = 'UIKit', 'AVFoundation', 'AVKit'
  s.dependency 'ObjectMapper', '~> 3.5.0'
  s.dependency 'SwiftyJSON'
  s.dependency 'SwiftyUserDefaults', '~> 4.0'
  s.dependency 'AlamofireImage'
  s.dependency 'iCarousel'
  s.dependency 'IQKeyboardManagerSwift','~> 6.0.4'
  s.dependency 'PullToRefreshKit'
  s.dependency 'UIScrollView-InfiniteScroll'
  s.dependency 'Firebase/Core'
  s.dependency 'Firebase/Database'
  s.dependency 'Firebase/Messaging'
  s.dependency 'FirebaseInstanceID'
  s.dependency 'Firebase/Performance'
  s.dependency 'GoogleMaps'
  s.dependency 'GooglePlaces'
  s.dependency 'Toast-Swift'
  s.dependency 'OpenTok'
  s.dependency 'HCSStarRatingView', '~> 1.5'
  s.dependency 'SwiftDate', '~> 6.0.3'
  s.dependency 'Collection'
  s.dependency 'Realm'
  s.dependency 'RealmSwift'
  s.dependency 'EasyDate'
  s.dependency 'UIColor-HexString'
  s.dependency 'Masonry'
  s.dependency 'DCAnimationKit'
  s.dependency 'OAuthSwift', '~> 1.4.1'
  s.dependency 'GooglePlacePicker'
  s.dependency 'BMPlayer', '~> 1.3.0'
  s.dependency 'libPhoneNumber-iOS', '~> 0.8'
  s.dependency 'PDFGenerator', '~> 3.0'
  s.dependency 'Popover'
  s.dependency 'Floaty', '~> 4.2.0'
  s.dependency 'JGProgressHUD'
  s.dependency 'EmptyDataSet-Swift', '~> 4.2.0'
  s.dependency 'BlinkAnimationKit'
  s.dependency 'Fabric'
  s.dependency 'Crashlytics'
  s.dependency 'CLImageEditor/AllTools'
  s.dependency 'iOSPhotoEditor'
  s.dependency 'SwiftyGif', '~> 4.2.0'
  s.dependency 'Siren'
  s.dependency 'CreditCardForm', :git => 'https://github.com/orazz/CreditCardForm-iOS.git', :commit => '550276f3ebbb0b1296caa106cf99f4128fe17cec'
  s.dependency 'Stripe'
  s.dependency 'Nuke', '~> 7.6.3'
  s.dependency 'PXSiriWave', '~> 0.0.2'
  s.dependency 'ESTabBarController-swift'
  s.dependency 'pop', '~> 1.0'
  s.dependency 'RxSwift', '~> 5.0'
  s.dependency 'RxCocoa', '~> 5.0'
  s.dependency 'RxAlamofire', '~> 5.0'
  s.dependency 'RxDataSources', '~> 4.0'
  s.dependency 'LightboxV2'
  s.dependency 'NVActivityIndicatorView'
  s.dependency 'FloatingPanel'
  s.dependency 'JKCalendar'
  s.dependency 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :tag => '4.0.0'
  s.dependency 'ZDCChat'
  s.dependency 'AnswerBotSDK', :git => 'https://github.com/zendesk/answer_bot_sdk_ios.git', :tag => '1.1.0'
  s.dependency 'pointzi'
  s.dependency 'paper-onboarding-pointzi'
  s.dependency 'SwiftKeychainWrapper'
  s.dependency 'AppCenter/Distribute'
end
