# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def core_pods
  pod 'ObjectMapper', '~> 3.5.0'
  pod 'SwiftyJSON'
  pod 'SwiftyUserDefaults', '~> 4.0'
  pod 'AlamofireImage'
  pod 'iCarousel'
  pod 'IQKeyboardManagerSwift','~> 6.0.4'
  pod 'PullToRefreshKit'
  pod 'UIScrollView-InfiniteScroll'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'FirebaseInstanceID'
  pod 'Firebase/Performance'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Toast-Swift'
  pod 'OpenTok'
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'SwiftDate', '~> 6.0.3'
  pod 'Collection'
  pod 'RealmSwift'
  pod 'EasyDate'
  pod 'UIColor-HexString'
  pod 'Masonry'
  pod 'DCAnimationKit'
  pod 'OAuthSwift', '~> 1.4.1'
  pod 'GooglePlacePicker'
  pod 'BMPlayer', '~> 1.3.0'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'PDFGenerator', '~> 3.0'
  pod 'Popover'
  pod 'Floaty', '~> 4.2.0'
  pod 'JGProgressHUD'
  pod 'EmptyDataSet-Swift', '~> 4.2.0'
  pod 'BlinkAnimationKit'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'CLImageEditor/AllTools'
  pod 'iOSPhotoEditor'
  pod 'SwiftyGif', '~> 4.2.0'
  pod 'Siren'
  pod 'CreditCardForm', :git => 'https://github.com/orazz/CreditCardForm-iOS.git', :commit => '550276f3ebbb0b1296caa106cf99f4128fe17cec'
  pod 'Stripe'
  pod 'Nuke', '~> 7.6.3'
  pod 'PXSiriWave', '~> 0.0.2'
  pod 'ESTabBarController-swift'
  pod 'pop', '~> 1.0'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxAlamofire', '~> 5.0'
  pod 'RxDataSources', '~> 4.0'
  pod 'LightboxV2'
  pod 'NVActivityIndicatorView'
  pod 'FloatingPanel'
  pod 'JKCalendar'
  pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :tag => '4.0.0'
  pod 'ZDCChat'
  pod 'AnswerBotSDK', :git => 'https://github.com/zendesk/answer_bot_sdk_ios.git', :tag => '1.1.0'
  pod 'pointzi'
  pod 'paper-onboarding-pointzi'
  pod 'SwiftKeychainWrapper'
  pod 'AppCenter/Distribute'
  
end

target 'BricksAndAgentPods' do
  core_pods
end
